batch_size = 32
epochs = 200
lr = 0.01
momentum = 0.9
no_cuda =False
cuda_id = '3'
seed = 1
log_interval = 10
l2_decay = 5e-4
class_num = 31
param = 0.3
bottle_neck = False
root_path = "/data/zyc/office31/"
source_name = "amazon"
target_name = "webcam"
ratio = 1
